---
name: GiftCode
version: 2.0.0
main: MrxKun\GiftCode\Main
api: 5.18.0
src-namespace-prefix: MrxKun\GiftCode
depend: ["BedrockEconomy"]
commands:
  giftcode:
    description: Open the gift code redemption form
    usage: "/giftcode"
    permission: giftcode.use
  giftcodegen:
    description: Open the gift code generation form
    usage: "/giftcodegen"
    permission: giftcode.gen
  giftcodedelete:
    description: Open the gift code deletion form
    usage: "/giftcodedelete"
    permission: giftcode.delete

permissions:
  giftcode.use:
    description: Allows players to use gift codes
    default: true
  giftcode.gen:
    description: Allows players to generate gift codes
    default: op
  giftcode.delete:
    description: Allows players to delete gift codes
    default: op
...
